#lang racket

(require (file "../../pda-to-pda-risc/macro-glue.rkt")
         (for-syntax racket/file racket/match))
(provide pda-term->pda pda->racket)

(define-syntax (pda-term->pda stx)
  (define (list-of-len v n [a '()])
    (if (> n 0) (list-of-len v (sub1 n) (cons v a)) a))
  (define (pda-mod pda)
    (let ((toks (cdar pda)))
      (foldr (λ (n a) (match n
                        (`(NO-SHIFT ,b ...)
                         `((EOS ,@b) (START s0) . ,a))
                        (`(RULE ,rn ,nt ,n (lambda ,args ,body))
                         `((RULE ,rn ,nt ,args ,body) . ,a))
                        (`(RULE ,rn ,nt ,n ,v)
                         `((RULE ,rn ,nt ,(list-of-len v n) ,v) . ,a))
                        (_ (cons n a))))
             '()
             pda)))
  (syntax-case stx ()
    ((_ clauses)
     #`'(#,@(pda-mod (syntax->datum #'clauses))))))

(define-syntax (pda->racket stx)
  (define (get-procs path)
    (if (file-exists? path)
        (file->value path #:mode 'text)
        (error 'pda->racket (format "no such file: ~a~n" path))))
  (syntax-case stx ()
    ((_ file pda-data)
     (let ((the-pda (syntax->datum #'pda-data)))
       (datum->syntax stx `(define parser (pda ,@(get-procs (syntax->datum #'file)) ,the-pda)))))))
