#!/bin/bash

# need better lexer

read -d '' PDA
if [ ! -n "$PDA" ]; then
    echo "Expected a PDA term from STDIN."
    exit 1
else
    PDA=${PDA:1} # cut off the '
    if [ $# -eq 2 ]; then
        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
        echo '#lang racket
(require (file "'$DIR'/macros.rkt")
         (file "'$DIR'/../../pda-to-pda-risc/macro-glue.rkt"))
(pda->racket "'$1'" '$PDA')
(define (str->list s)
  (if (eof-object? s)
      (exit)
      (map (λ (x) (let ((num (string->number x)))
                    (if num num (string->symbol x))))
           (string-split s " "))))
(define (loop)
  (begin (let* ((s (read-line))
                (l (str->list s)))
           (if (zero? (length l))
               (exit)
               (display (format "~a~n" (parser l)))))
               (loop)))
(loop)
' > $2.rkt
        raco exe $2.rkt
        rm $2.rkt
        exit 0
    else
        echo 'Usage: racket->exe procs.procs out'
        exit 1
    fi
fi
